### ISSUE TITLE
Optionally allow as much computation with CUDA as possible

### ISSUE THREAD

**Issue by emprice** [probabilists/zuko#58]
### Description

Since PyTorch has the ability to perform tensor operations on a CUDA device, and zuko is built on PyTorch, there is no reason why a zuko flow could not be trained on GPU. This may provide a substantial performance increase when accelerator hardware is available.

### Implementation

Most tensor operations can be carried out with CUDA already. Exceptions may include integer matrix multiply, which does not appear to be supported by PyTorch. Any operation that cannot be performed on GPU should be done on CPU and then migrated if needed.

### Alternatives

No alternatives considered at this time.

**Comment by francois-rozet** [comment]
Hello @emprice, thank you for raising this issue.

Zuko already supports training on CUDA. You can take any Zuko module and transfer them to CUDA like you would normal PyTorch modules.

```python
from zuko.flows import MAF

flow = MAF(3, 5)
flow.to("cuda")
```

However, you are right that not all computations, especially the initializations, support CUDA currently. This becomes an issue when the default device is set to CUDA. I agree that this should be fixed. I will take a look at your PR.
